# .github/workflows/main.yml

name: Main Workflow

on:
  push:
    branches:
      - main
    paths:
      - requirements.txt
      - .github/workflows/testing/test_import_libraries.py
      - .github/workflows/main.yml

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest] #ubuntu-22.04, ubuntu-20.04]
        python-version: [3.9,3.11.3] #[3.9,3.11.3,3.12]
        # arch: [arm64, amd64]


    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Use External Template
        run: |
         curl -sS https://raw.githubusercontent.com/Nouri-organization/workflow_templates/main/test_template.yml | bash
    
