# .github/workflows/main.yml

name: Main Workflow

on:
  push:
    branches:
      - main
    paths:
      - requirements.txt
      - .github/workflows/testing/test_import_libraries.py

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use External Template
        run: |
         curl -sS https://raw.githubusercontent.com/Nouri-organization/workflow_templates/main/test_template.yml | bash
    
