# .github/workflows/main.yml

name: Main Workflow

on:
 workflow_dispatch:
   inputs:
      external_template:
        description: 'Include external template'
        required: false

  # push:
  #   branches:
  #     - main
  #   paths:
  #     - requirements.txt
  #     - .github/workflows/testing/test_import_libraries.py
  #     - .github/workflows/main.yml

jobs:
  test_template:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest] #ubuntu-22.04, ubuntu-20.04]
        python-version: [3.11.3] #[3.9,3.11.3,3.12]
        # arch: [arm64, amd64]


    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Use External Template
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          REPO: Nouri-organization/workflow_templates
          EVENT_TYPE: workflow_dispatch
        #   CLIENT_PAYLOAD: '{"param1": "value1", "param2": "value2", "param3": "value3"}'
        run: |
         content=$(curl -sS https://raw.githubusercontent.com/Nouri-organization/workflow_templates/main/.github/workflows/test_template.yml) 
         echo "Content of test_template.yml:"
         echo "$content"
         echo "$content" > external-template.yml 
          
         curl -X POST \
           -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
           -H "Accept: application/vnd.github.everest-preview+json" \
           -H "Content-Type: application/json" \
           https://api.github.com/repos/Nouri-organization/workflow_templates/actions/workflows/test_template.yml/dispatches \
           -d '{"ref": "main", "inputs": {"external_template": "'"$content"'"}}'
           
           

   # content=$(curl -sS https://raw.githubusercontent.com/Nouri-organization/workflow_templates/main/test_template.yml)
   # echo "$content" > test_template.yml          
   # -d '{"ref": "main", "inputs": {"external_template": "$content"}}' 

        
        # run: |
        #  curl -sS https://raw.githubusercontent.com/Nouri-organization/workflow_templates/main/test_template.yml
 #| bash
        
 # curl -sS https://raw.githubusercontent.com/Nouri-organization/workflow_templates/main/test_template.yml -o external-template.yml

# curl -L \
#   -X POST \
#   -H "Accept: application/vnd.github+json" \
#   -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
#   -H "Content-Type: application/json" \
#   -d '{"ref": "main", "inputs": {"external_template": "$(cat external-template.yml )"}}' \
#   https://api.github.com/repos/REPO/actions/workflows/test_template.yml/dispatches
   
